name: workflow
on:
  push:
  workflow_dispatch:
    inputs:
      module_name:
        type: choice
        required: true
        options:
          - trinh
          - ghe

jobs:
  env:
    name: env
    runs-on: ubuntu-latest
    steps:
      - name: test env variables
        run: echo "Hello ${{inputs.module_name}} ${{inputs.module_name}}"
